import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="min-h-screen bg-gray-50 text-gray-900">
        <header className="border-b bg-white">
          <div className="mx-auto flex h-14 w-[1190px] items-center justify-between">
            <h1 className="text-[18px] font-bold">Next Practice</h1>

            <nav className="flex gap-5 text-[13px] font-medium text-gray-600">
              <Link href="/">Home</Link>
              <Link href="/posts">Posts</Link>
              <Link href="/login">Login</Link>
              <Link href="/mypage">My Page</Link>
            </nav>
          </div>
        </header>

        <main className="mx-auto min-h-[calc(100vh-112px)] w-[1190px] py-8">
          {children}
        </main>

        <footer className="border-t bg-white">
          <div className="mx-auto flex h-14 w-[1190px] items-center text-[12px] text-gray-500">
            © 2026 Next Practice
          </div>
        </footer>
      </body>
    </html>
  );
}
